version: 2
updates:
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/functions"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
